#!/bin/sh
#
# Inspect the commit message to ensure that it adheres to the following.
#
# 1. Subject line character count is less than or equal to 50.
# 2. A ticket reference is not in the subject line.
# 3. A ticket reference is provided on a newline.
#
# If any of the above are not met, the commit will abort. For those who wrote a
# long commit message only to have it aborted, it can be found at .git/COMMIT_EDITMSG
#
# @author matthew.greenfield@opower.com
#

MESSAGE_FILE=$1
SUBJECT_LINE=$( head -n1 $MESSAGE_FILE )

SUBJECT_CHARACTER_COUNT=$( echo $SUBJECT_LINE | wc -m | tr -d '[[:space:]]' )
if [ $SUBJECT_CHARACTER_COUNT -gt 50 ]; then
  echo "[POLICY] Your message contains a subject line that is too long"
  exit 1
fi

echo $SUBJECT_LINE | grep -i -E '([A-Z]{2,}-[0-9]+\n?|NO-REF)' > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "[POLICY] The subject line of your message shouldn't contain a ticket ref"
  exit 1
fi

# NOTE: the following regex starts with '^'
cat $MESSAGE_FILE | grep -i -E '^([A-Z]{2,}-[0-9]+\n?|NO-REF)' > /dev/null 2>&1
if [ $? -ge 1 ]; then
  echo "[POLICY] Your message should contain a ticked number on a separate line"
  exit 1
fi
