#!/bin/sh
#
# Detect projects with some sort of changelog file, alerting the committer before committing.
#
# If the $CHANGELOG_FILE does not exist, do nothing.
# If the $CHANGELOG_FILE exists and it has
#     - been modified, do nothing. Presumably, PR reviewers will notice any mistakes.
#     - not been modified, prompt the user if they would like to continue.
#
# @author matthew.greenfield@opower.com
#

GIT_ROOT=$(git rev-parse --show-toplevel)
CHANGELOG_FILENAME=$(ls $GIT_ROOT | grep -i -E '(release.?notes?|changes?.?log|changelog|changes)' )
CHANGELOG_FILE="$GIT_ROOT/$CHANGELOG_FILENAME"

if [ "$CHANGELOG_FILENAME" == "" ]; then
  exit 0
fi

CHANGES=$(git diff --staged "$CHANGELOG_FILE" | tr -d '[[:space:]]')
if [ "$CHANGES" != "" ]; then
  exit 0
fi

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

while true; do
  read -p "No changes made to $CHANGELOG_FILE. Continue? (Y/n) " yn
  if [ "$yn" = "" ]; then
    yn='N'
  fi
  case $yn in
      [Yy] ) exit 0;;
      [Nn] ) echo "Please update $CHANGELOG_FILE before continuing"; exit 1;;
      * ) echo "Please answer y or n for yes or no.";;
  esac
done

