#!/bin/sh
#
# Inspects the branch name to see if it matches the Opower ticket ref format. If
# the branch matches the ticket format, the ticket ref is automatically added to
# the commit message.
#
# @author matthew.greenfield@opower.com
#

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="${BRANCH_NAME##*/}"

# If the branch name uses '_', that's ok, we'll change it to '-' in the message.
echo $BRANCH_NAME | grep -i -E '^([A-Z]{2,}[-_][0-9]+\n?|NO-REF)$' > /dev/null 2>&1
if [ $? -eq 0 ]; then
  grep $BRANCH_NAME $1 > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    sed -i.bak -e "1s/^/$BRANCH_NAME/" -e "1s/_/-/" $1
  fi
fi
