#!/usr/bin/env bash

set -e
set -u
set -o pipefail

if [ ! -d "$ZSH" ]; then
  echo 'Installing oh-my-zsh'
  curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh > /tmp/install.sh
  sh /tmp/install.sh --unattended
else
  echo 'oh-my-zsh already installed'
fi

echo 'Configuring oh-my-zsh'
rm ~/.zshrc
cp ~/dots/.zshrc ~/.zshrc

rm -rf ${ZSH_CUSTOM:-~/.oh-my-zsh/custom/}
git clone --quiet https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone --quiet https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

echo 'Configuring tmux'
cp ~/dots/.tmux.conf ~/.tmux.conf

echo 'Configuring alacritty'
cp ~/dots/.alacritty.yml ~/.alacritty.yml

echo 'Configuring git'
cd ~
rm ~/.gitignore
cp ~/dots/.gitignore ~/.gitignore

echo 'Configuring vim'
rm -rf ~/.vim/
cp ~/dots/.vimrc ~/.vimrc
git clone --quiet https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

echo 'Configuring MySQL'
cp ~/dots/.my.cnf ~/.my.cnf

