#!/usr/bin/env bash

set -e
set -u
set -o pipefail

cp ~/dots/.my.cnf ~/.my.cnf

# Install vim (brew managed vim recommended to get a recent version)
rm -rf ~/.vim/
cp ~/dots/.vimrc ~/.vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# Install Git configuration
cd ~
cp ~/dots/.gitignore ~/.gitignore
echo 'Installing Git Completion'
curl -s https://github.com/git/git/raw/master/contrib/completion/git-completion.bash -OL -o ~/git-completion.bash

echo 'Installing Git Prompt'
curl -s https://github.com/git/git/raw/master/contrib/completion/git-prompt.sh -OL -o ~/git-prompt.sh

