#!/usr/bin/env ruby
message_file = ARGV[0]
message = File.read(message_file)

$regex = /([A-Z]{2,}-[0-9]+\n?|NO-REF)/

if !$regex.match(message)
  puts "[POLICY] Your message is not formatted correctly"
  exit 1
end
