#!/usr/bin/env bash

set -e
set -u
set -o pipefail

DEFAULT_RUBY_VERSION=2.3.3

# Requires brew to have installed rbenv and ruby-build
mkdir -p ~/.rbenv
echo "$DEFAULT_RUBY_VERSION" >> ~/.rbenv/version

RBENV_EXPORT='export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"'
if ! grep -q $RBENV_EXPORT "$HOME/.profile" ; then
  echo $RBENV_EXPORT >> ~/.profile
  echo 'eval "$(rbenv init -)"' >> ~/.profile
fi

RBENV_DEFAULT_GEMS_PATH="$(rbenv root)/plugins/rbenv-default-gems"
rm -rf "$RBENV_DEFAULT_GEMS_PATH"
git clone https://github.com/rbenv/rbenv-default-gems.git "$(rbenv root)/plugins/rbenv-default-gems"

DEFAULT_GEMS_PATH="$(rbenv root)/default-gems"
rm "$DEFAULT_GEMS_PATH"
echo bundler >> "$DEFAULT_GEMS_PATH"
echo gem-ctags >> "$DEFAULT_GEMS_PATH"

rbenv install "$DEFAULT_RUBY_VERSION"
